# Generated by Django 5.1.4 on 2024-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
         ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_patient", models.BooleanField(default=True)),
                ("is_doctor", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
    ]
