# Generated by Django 5.1.4 on 2024-12-13 07:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hospital", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_patient", models.BooleanField(default=False)),
                ("is_doctor", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=10)),
                ("registration_no", models.CharField(max_length=100)),
                ("year_of_registration", models.DateField()),
                ("qualification", models.CharField(max_length=100)),
                ("State_Medical_Council", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=50)),
                ("rating", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="patient",
            name="id",
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="diseaseinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diseasename", models.CharField(max_length=200)),
                ("no_of_symp", models.IntegerField()),
                (
                    "symptomsname",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=5)),
                ("consultdoctor", models.CharField(max_length=200)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consultation_date", models.DateField()),
                ("status", models.CharField(max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.patient",
                    ),
                ),
                (
                    "diseaseinfo",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.diseaseinfo",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="rating_review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("review", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.patient",
                    ),
                ),
            ],
        ),
    ]
