# Generated by Django 5.1.4 on 2024-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0002_doctor_remove_patient_id_patient_user_diseaseinfo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="registration_no",
            field=models.CharField(max_length=50),
        ),
    ]
