# Generated by Django 5.1.4 on 2024-12-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_alter_doctor_registration_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=500),
        ),
    ]
